ssh:
  shell:
    enable: on
    # 'simple' or 'security'
    authentication: simple
    # if authentication set to 'security' the AuthenticationProvider bean name
    # if not specified and only one AuthenticationProvider bean is present in the context, it will be used
    auth-provider-bean-name:
    # since 1.2.2, optional file containing authorized public keys (standard authorized_keys format, one key per line
    # starting with 'ssh-rsa'), takes precedence over authentication (simple or not)
    authorized-public-keys-file:
    # since 1.5.5, optional spring resource containing authorized public keys (file:, classpath: , etc)
    # note: in case of a non file resource, a temporary file is created with given content and deleted on process exit
    # this is due to ssh external library which only accepts file in api
    authorized-public-keys:
    # for ssh helper 'confirm' method
    confirmation-words:
      - y
      - yes
    # since 1.4.0, set enable to false to disable following default commands
    commands:
      actuator:
        create: off
        enable: off
        restricted: off
        # empty by default
        excludes:
          - ...
        authorized-roles:
          - ACTUATOR
      # since 1.4.0
      jmx:
        create: on
        enable: on
        restricted: on
        authorized-roles:
          - ADMIN
      system:
        create: on
        enable: on
        restricted: on
        authorized-roles:
          - ADMIN
      # since 1.4.0
      datasource:
        create: true
        enable: true
        restricted: true
        authorized-roles:
          - ADMIN
        excludes:
          - datasource-update
      postprocessors:
        create: true
        enable: true
        restricted: false
      # since 1.3.0, command which allows you to list ssh sessions, and stop them
      manage-sessions:
        create: true
        enable: false
        restricted: true
        authorized-roles:
          - ADMIN
      # since 1.5.0
      tasks:
        create: true
        enable: false
        restricted: false
        authorized-roles:
          - ADMIN
    display-banner: true
    # to use ExtendedFileValueProviderTest instead of spring shell FileValueProvider for all File option parameters
    # if set to false, it still can be used via '@ShellOption(valueProvider = ExtendedFileValueProviderTest.class) File file'
    extended-file-provider: true
    history-file: ${home}/sshShellHistory.log
    # since 1.3.0, set to false to have one file per user (<history-directory>/sshShellHistory-<user>.log)
    shared-history: true
    # since 1.3.0, only if shared-history is set to false
    history-directory: ${home}
    host: 127.0.0.1
    host-key-file: ${home}/hostKey.ser
    # displayed in log if generated
    password:
    port: 2222
    user: user
    prompt:
      # in enum: com.github.fonimus.ssh.shell.PromptColor (black, red, green, yellow, blue, magenta, cyan, white, bright)
      color: white
      text: 'shell>'
      local:
        # since 1.2.1, to let default local spring shell prompt when application starts
        enable: false
project:
  version: 1.0.0