logging:
  level:
    # swagger 警告日志忽略
    io.swagger.models.parameters.AbstractSerializableParameter: error
    org.springframework: warn
log:
  file:
    path: ${HOME}/logs

opscloud:
  version: 4.2.0
  dataPath: ${HOME}/opscloud-data
  createUser:
    roles:
      - base
    userGroups:
      - vpn-users
      - confluence-users
  outapi:
    workorder:
      approval: 'http://127.0.0.1:8080/api/out/ticket/approve?ticketId=%s&username=%s&approvalType=%s&token=%s'

terminal:
  audit:
    # on 开启审计日志 off 关闭审计日志
    open: on
    # 审计日志目录
    path: ${HOME}/opscloud-data/ssh/audit

spring:
  config:
    activate:
      on-profile:
        - local
  redis:
    host: ENC(hOL0LX7EFVBNlLXqSaZV2rYKC2vcPGJ7)
    # host: r-d7obmf3lmgs0hpph5n.redis.eu-west-1.rds.aliyuncs.com
    port: 6379
    password: ENC(5w2StO4dbBR/gLwjK0uuomVfN5vORxJn3GW5nPsIucDgD7TvGnMfVw==)
    # password: ENC(o6UKSKlETx2g13HH0nsWttoQSvW0+OF/7/DcHo2lc0FOlf03x8jzTgB1khTUODtXRMzG2/PK8uQ=)
    jedis:
      pool:
        max-wait: 5000
        max-idle: 20
        max-active: 100
        min-idle: 0
  datasource:
    druid:
      opscloud:
        url: jdbc:mysql://127.0.0.1:3306/opscloud4?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&useInformationSchema=true&tinyInt1isBit=true&nullCatalogMeansCurrent=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
        username: opscloud4
        password: '5YOHmsr4O2'
        initial-size: 5
        min-idle: 5
        max-active: 50
        # 获取连接时最大等待时间，单位毫秒。配置了maxWait之后，缺省启用公平锁，并发效率会有所下降，如果需要可以通过配置useUnfairLock属性为true使用非公平锁。
        max-wait: 1000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        time-between-eviction-runs-millis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        min-evictable-idle-time-millis: 300000
        # 用来检测连接是否有效的sql
        validation-query: select 1
        # 申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效
        test-while-idle: on
        # 申请连接时执行validationQuery检测连接是否有效, 默认on:检测, off:不检测
        test-on-borrow: off
        # 归还连接时执行validationQuery检测连接是否有效, 默认off:不检测, on:检测
        test-on-return: off
        # 打开PSCache(preparedStatement)，并且指定每个连接上PSCache的大小
        pool-prepared-statements: on
        # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true
        max-pool-prepared-statement-per-connection-size: 20

# java -jar -Djasypt.encryptor.password=${password}
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: 'org.jasypt.iv.NoIvGenerator'