spring:
  application:
    name: opscloud
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  jmx:
    enabled: false
  profiles:
    active: '@env@'

management:
  server:
    ssl:
      enabled: off
  health:
    ldap:
      enabled: off

knife4j:
  enable: true

# 白名单配置
white:
  urls:
    - /*.js
    - /*.css
    - /*.jpg
    - /*.ico
    - /swagger-resources
    - /swagger-ui.html
    - /v2/api-docs
    - /doc.html
    - /api/ws/guacamole/tunnel
    - /api/ws/terminal
    - /api/ws/kubernetes/terminal
    - /api/ws/terminal/session/audit
    - /api/ws/server/task/play
    - /api/ws/jenkins/build/executor/status
    - /api/out/ticket/approve

# 开发环境配置
server:
  # 服务端口
  port: 8080
  servlet:
    # 项目contextPath
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    accept-count: 400
    max-connections: 800
    max-http-form-post-size: 209715200
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值25
      min-spare: 25

mapper:
  mappers:
    - tk.mybatis.mapper.common.Mapper
  not-empty: true
  identity: MYSQL
  before: false

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

# mybatis
mybatis:
  type-aliases-package: com.baiyi.opscloud.domain
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

# ssh-server
ssh:
  arthas:
    server: "cd /tmp && curl -O https://arthas.aliyun.com/arthas-boot.jar && sudo su - app -c 'java -jar /tmp/arthas-boot.jar'\n"
  shell:
    enable: true
    # 'simple' or 'security'
    authentication: security
    # if authentication set to 'security' the AuthenticationProvider bean name
    # if not specified and only one AuthenticationProvider bean is present in the context, it will be used
    confirmation-words:
      - y
      - yes
    # since 1.4.0, set enable to false to disable following default commands
    commands:
      actuator:
        create: false
        enable: false
        restricted: false
        # empty by default
        excludes:
          - ...
        authorized-roles:
          - ACTUATOR
    display-banner: true
    # to use ExtendedFileValueProviderTest instead of spring shell FileValueProvider for all File option parameters
    # if set to false, it still can be used via '@ShellOption(valueProvider = ExtendedFileValueProviderTest.class) File file'
    extended-file-provider: false
    history-file: ${home}/opscloud-data/ssh-server/sshShellHistory.log
    # since 1.3.0, set to false to have one file per user (<history-directory>/sshShellHistory-<user>.log)
    shared-history: false
    # since 1.3.0, only if shared-history is set to false
    history-directory: ${home}/opscloud-data/ssh-server
    host-key-file: ${home}/opscloud-data/ssh-server/hostKey.ser
    # displayed in log if generated
    port: 2222
    prompt:
      # in enum: com.github.fonimus.ssh.shell.PromptColor (black, red, green, yellow, blue, magenta, cyan, white, bright)
      color: white
      text: 'ssh-server>'
      local:
        # since 1.2.1, to let default local spring shell prompt when application starts
        enable: false
